# =========================
# DATASET CONFIGURATION
# =========================
dataset:
  train_csv: "/sub-paritions/p1/sieut/graph/Graph_Research/data_zip/si/train.csv"
  val_csv: "/sub-paritions/p1/sieut/graph/Graph_Research/data_zip/si/dev.csv"
  pose_pkl: "/sub-paritions/p1/sieut/graph/Graph_Research/data_zip/si/pose_data_isharah1000_hands_lips_body_May12.pkl"
  delimiter: ","
  min_len: 32
  max_len: 1000
  additional_joints: true
  augment: true
  augment_prob: 0.5
  tokenizer_type: "seq2seq"   # "ctc" hoặc "seq2seq"

# =========================
# MODEL CONFIGURATION
# =========================
model:
  name: "CSLRTransformerAutoregressivePermutate"
  input_dim: 172   # Số joints * 2 (nếu pose là [B, T, 43, 2] thì 43*2=86)
  hidden_dim: 512
  num_layers: 2
  encoder_num_heads: 8
  decoder_num_heads: 8
  num_decoder_layers: 2
  dec_mlp_ratio: 4
  refine_iters: 3
  conv_channels: 512
  mlp_hidden: 512
  dropout: 0.1
  max_input_len: 1000    # <-- Độ dài sequence đầu vào (encoder)
  max_output_len: 12    # <-- Độ dài sequence đầu ra (decode/inference)

# =========================
# TRAINER CONFIGURATION
# =========================
trainer:
  batch_size: 8
  num_workers: 8
  epochs: 300
  lr: 0.0005
  weight_decay: 0.01
  warmup_pct: 0.1
  device: "cuda"
  seed: 42
  # save_dir: "./checkpoints/"
  log_interval: 50
  # log_interval_step: 100
  check_val_every_n_epoch: 3
  devices: 1
# =========================
# LOGGING & MISC
# =========================
logging:
  log_dir: "./logs"
  print_config: true
